
<div class="page-content">
    <h1 style="float:right;">this is where the content of dat base should be presented</h1>

<a style="float:right;"  href="/">home</a>
<div class="scroll">
    
<table>
    <tr>
        <th>h</th>
        <th>h</th>
        <th>h</th>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr><tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
    <tr>
        <td>t</td>
        <td>t</td>
        <td>t</td>
    </tr>
</table>
</div>
</div>

<!-- for here to a table and hit the over flow in the x or maby y direction
 ps try to find out how to over lay element swith keeps the conectivity//interactivity of the bottom element-->

 <style>
    .scroll{
        max-height: 90vh;
        width: 20%;
        overflow-y: auto;
        background-color: #080808;
    }
    table{
        width:inherit;
        border-collapse: collapse;
    }
    .page-content{
        margin: 0;
        padding: 0;
        height: inherit;
    }
 </style>